Download docker-compose if needed

diff --git a/spnctl b/spnctl
--- a/spnctl
+++ b/spnctl
@@ -1,7 +1,22 @@
 #!/usr/bin/env bash
 
-# TODO check that docker-compose is installed
 # TODO download bb into ./bin/bb
+set -e
+
+die () {
+    echo >&2 -e "$*"
+    exit 1
+}
+
+docker_version="1.29.2"
+
+docker_compose=$(command -v docker-compose)
+if [[ "${docker_compose}" == "" ]]; then
+    echo >&2 "Missing required dependency: docker-compose; downloading it..."
+    docker_compose="$(pwd)/bin/docker-compose"
+    curl -L "https://github.com/docker/compose/releases/download/${docker_version}/docker-compose-$(uname -s)-$(uname -m)" -o "${docker_compose}"
+    chmod 755 "${docker_compose}"
+fi
 
 bb=$(pwd)/bin/bb
 
@@ -9,5 +24,7 @@ if [[ $# = 0 ]]; then
     $bb --tasks
     exit
 fi
+
+export PATH="$(pwd)/bin:$PATH"
 
 "${bb}" run $@
