Don't unnecessarily re-download docker-compose

diff --git a/spnctl b/spnctl
--- a/spnctl
+++ b/spnctl
@@ -18,8 +18,11 @@ mkdir -p bin
 
 docker_compose=$(command -v docker-compose || true)
 if [[ "${docker_compose}" == "" ]]; then
-    echo >&2 "Missing required dependency: docker-compose; downloading it..."
     docker_compose="$(pwd)/bin/docker-compose"
+fi
+
+if [[ ! -f "${docker_compose}" ]]; then
+    echo >&2 "Missing required dependency: docker-compose; downloading it..."
     curl -sS -L "https://github.com/docker/compose/releases/download/${docker_compose_version}/docker-compose-$(uname -s)-$(uname -m)" -o "${docker_compose}"
 
     echo "Verify checksum..."
