Die if curl is missing

diff --git a/spnctl b/spnctl
--- a/spnctl
+++ b/spnctl
@@ -10,6 +10,8 @@ die () {
 
 docker_version="1.29.2"
 
+command -v curl > /dev/null || die "Missing required dependency: curl"
+
 docker_compose=$(command -v docker-compose)
 if [[ "${docker_compose}" == "" ]]; then
     echo >&2 "Missing required dependency: docker-compose; downloading it..."
