Correct docker_compose_version variable name typo

diff --git a/spnctl b/spnctl
--- a/spnctl
+++ b/spnctl
@@ -31,7 +31,7 @@ if [ -e "${docker_compose}" ]; then
 fi
 
 if [ "${min_docker_compose_version}" != "$(echo -e "${installed_docker_compose_version}\n${min_docker_compose_version}" | sort -V | head -n1)" ]; then
-    echo >&2 "Missing or old version of required dependency: docker-compose; downloading docker-compose version ${docker-compose_version}..."
+    echo >&2 "Missing or old version of required dependency: docker-compose; downloading docker-compose version ${docker_compose_version}..."
     curl -sS -L "https://github.com/docker/compose/releases/download/${docker_compose_version}/docker-compose-$(uname -s)-$(uname -m)" -o "${docker_compose}"
 
     echo "Verify checksum..."
